'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Concession
    Public Property Id As Integer
    Public Property Numero As Nullable(Of Integer)
    Public Property DateDebut As Nullable(Of Date)
    Public Property DateFin As Nullable(Of Date)
    Public Property NbreRenovations As Nullable(Of Integer)
    Public Property MontantPaye As Nullable(Of Decimal)
    Public Property EmplId As Integer
    Public Property CsnrId As Integer
    Public Property ComId As Nullable(Of Integer)

    Public Overridable Property Concessionnaire As Concessionnaire
    Public Overridable Property Commentaire As Commentaire
    Public Overridable Property Emplacement As Emplacement
    Public Overridable Property Beneficiaires As ICollection(Of Beneficiaire) = New HashSet(Of Beneficiaire)

End Class
