'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Defunt
    Public Property Id As Integer
    Public Property NumeroLh As Nullable(Of Integer)
    Public Property NumeroAnnee As Nullable(Of Integer)
    Public Property Prenom As String
    Public Property Nom As String
    Public Property Adresse As String
    Public Property EtatCivil As TEtatCivil
    Public Property EtatCivilDe As String
    Public Property DateNaiss As Nullable(Of Date)
    Public Property LieuNaiss As String
    Public Property DateDeces As Nullable(Of Date)
    Public Property LieuDeces As String
    Public Property PcId As Nullable(Of Integer)
    Public Property DateDebut As Date
    Public Property DateFin As Nullable(Of Date)
    Public Property EmplId As Nullable(Of Integer)
    Public Property LocVilleId As Nullable(Of Integer)

    Public Overridable Property Emplacement As Emplacement
    Public Overridable Property LocVille As LocVille
    Public Overridable Property PersonneContact As PersonneContact

End Class
