'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class CimEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CimEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Beneficiaires() As DbSet(Of Beneficiaire)
    Public Overridable Property Concessionnaires() As DbSet(Of Concessionnaire)
    Public Overridable Property Concessions() As DbSet(Of Concession)
    Public Overridable Property Defunts() As DbSet(Of Defunt)
    Public Overridable Property Emplacements() As DbSet(Of Emplacement)
    Public Overridable Property PersonnesContact() As DbSet(Of PersonneContact)
    Public Overridable Property Commentaires() As DbSet(Of Commentaire)
    Public Overridable Property Histoires() As DbSet(Of Histoire)
    Public Overridable Property LocVilles() As DbSet(Of LocVille)
    Public Overridable Property Pays() As DbSet(Of Pays)

End Class
