'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LocVille
    Public Property Id As Integer
    Public Property Cp As Nullable(Of Integer)
    Public Property Ville As String
    Public Property PaysId As Nullable(Of Integer)

    Public Overridable Property Beneficiaires As ICollection(Of Beneficiaire) = New HashSet(Of Beneficiaire)
    Public Overridable Property Concessionnaires As ICollection(Of Concessionnaire) = New HashSet(Of Concessionnaire)
    Public Overridable Property Defunts As ICollection(Of Defunt) = New HashSet(Of Defunt)
    Public Overridable Property PersonnesContact As ICollection(Of PersonneContact) = New HashSet(Of PersonneContact)
    Public Overridable Property Pays As Pays

End Class
