'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Public Enum TEtatCivil As Integer
    NonPrecise = 0
    Celibataire = 1
    Epoux = 2
    Veuf = 3
    Divorce = 4
    Enfant = 5
End Enum
