'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Public Enum TTypeEmpl As Integer
    NonPrecise = 0
    Caveau = 1
    Concession = 2
    FosseOrdinaire = 3
End Enum
